"""
Method 3: Random Walk + Gaussian Smoothing terrain generator.

Terrain height generated by a biased random walk then smoothed with a
Gaussian kernel (implemented in pure numpy — no scipy required).
Gaps punched by a separate random process.

Character: jagged, unpredictable, locally irregular — unlike fBm which has
global smooth correlation, the random walk has strong local drift.
"""

from pathlib import Path
import numpy as np
from .terrain_common import (
    ENV_LEFT, ENV_RIGHT, ENV_FLOOR, BODY_LENGTH,
    render_terrain, save_terrain_json,
)

OUT_DIR = Path(__file__).parent / "outputs" / "random_walk"
METHOD  = "random_walk"

N_SAMPLES = 500


# ── Pure-numpy Gaussian filter ────────────────────────────────────────────────

def gaussian_filter1d(x: np.ndarray, sigma: float) -> np.ndarray:
    ks = int(6 * sigma + 1) | 1  # odd kernel size
    kx = np.arange(ks) - ks // 2
    kernel = np.exp(-kx ** 2 / (2 * sigma ** 2))
    kernel /= kernel.sum()
    return np.convolve(x, kernel, mode="same")


# ── Random walk terrain ───────────────────────────────────────────────────────

def random_walk_terrain(n: int, step_sigma: float, smooth_sigma: float,
                        amplitude: float, y_bias: float, seed: int) -> np.ndarray:
    rng = np.random.RandomState(seed)
    # Random walk with slight upward bias initially, then corrected
    steps = rng.normal(0.0, step_sigma, n)
    raw   = np.cumsum(steps)
    # Normalize to [0, amplitude]
    raw  -= raw.min()
    if raw.max() > 0:
        raw = raw / raw.max() * amplitude
    raw  += y_bias
    # Smooth
    ys = gaussian_filter1d(raw, smooth_sigma)
    ys = np.clip(ys, 0.0, 3.5)
    # Taper ends to 0
    fade = 40
    for i in range(fade):
        w = i / fade
        ys[i]        = ys[i] * w
        ys[-(i + 1)] = ys[-(i + 1)] * w
    return ys


def punch_gaps(xs: np.ndarray, n_gaps: int, min_w: float, max_w: float,
               seed: int) -> tuple[np.ndarray, list[tuple]]:
    rng  = np.random.RandomState(seed + 500)
    mask = np.ones(len(xs), dtype=bool)
    gaps = []
    candidates = xs[(xs > ENV_LEFT + 2.0) & (xs < ENV_RIGHT - 2.0)]
    placed = []
    for _ in range(n_gaps):
        w  = rng.uniform(min_w, max_w)
        for _ in range(30):
            cx = rng.uniform(candidates[0], candidates[-1])
            if not any(abs(cx - pc) < (pw + w) / 2 + 0.3 for pc, pw in placed):
                placed.append((cx, w))
                mask[(xs >= cx - w / 2) & (xs <= cx + w / 2)] = False
                gaps.append((cx - w / 2, cx + w / 2))
                break
    return mask, gaps


def vertices_to_segments(xs, ys, mask):
    segs = []
    for i in range(len(xs) - 1):
        if mask[i] and mask[i + 1]:
            segs.append(((float(xs[i]), float(ys[i])),
                         (float(xs[i + 1]), float(ys[i + 1]))))
    return segs


# ── 10 Configurations ─────────────────────────────────────────────────────────

CONFIGS = [
    # step_sigma, smooth_sigma, amplitude, y_bias, n_gaps, min_w, max_w, title
    (0.05, 15.0, 0.3, 0.1, 0,  0.0, 0.0, "very smooth walk, no gaps"),
    (0.08, 10.0, 0.5, 0.2, 3,  0.4, 0.7, "gentle walk + small gaps"),
    (0.12, 8.0,  0.8, 0.3, 2,  2.0, 3.0, "moderate walk + large gaps"),
    (0.15, 5.0,  1.0, 0.4, 4,  0.5, 0.8, "rougher walk + mixed small"),
    (0.20, 4.0,  1.2, 0.5, 2,  2.5, 3.5, "bumpy walk + 2 large gaps"),
    (0.25, 3.0,  1.5, 0.5, 5,  0.4, 2.5, "jagged walk + 5 varied gaps"),
    (0.10, 12.0, 0.6, 0.0, 6,  0.3, 0.7, "smooth walk + 6 small steppable"),
    (0.30, 2.0,  1.8, 0.6, 3,  2.2, 3.8, "very jagged + 3 large gaps"),
    (0.18, 6.0,  1.0, 0.2, 4,  0.6, 2.0, "medium jagged + borderline gaps"),
    (0.35, 1.5,  2.0, 0.8, 4,  2.0, 4.0, "max jagged + max gaps"),
]


def generate(seed: int) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cfg = CONFIGS[seed % len(CONFIGS)]
    step_sigma, smooth_sigma, amplitude, y_bias, n_gaps, min_w, max_w, title = cfg

    xs = np.linspace(ENV_LEFT, ENV_RIGHT, N_SAMPLES)
    ys = random_walk_terrain(N_SAMPLES, step_sigma, smooth_sigma, amplitude, y_bias, seed)

    mask, gaps = punch_gaps(xs, n_gaps, min_w, max_w, seed)
    segs = vertices_to_segments(xs, ys, mask)

    render_terrain(segs, gaps, title, METHOD, seed,
                   OUT_DIR / f"terrain_{seed:02d}.png")
    save_terrain_json(segs, gaps, OUT_DIR / f"terrain_{seed:02d}.json")
    print(f"  [{METHOD}] seed={seed}: {title}  segs={len(segs)} gaps={len(gaps)}")


def main():
    print(f"Generating {METHOD} terrains ...")
    for s in range(10):
        generate(s)
    print("Done.")


if __name__ == "__main__":
    main()
